/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as ShuihuWritingRouteImport } from './routes/shuihu-writing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchoolTingxieRouteImport } from './routes/school-tingxie'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RadicalsRouteImport } from './routes/radicals'
import { Route as PhraseMatchingRouteImport } from './routes/phrase-matching'
import { Route as P3hclWupinInteractiveRouteImport } from './routes/p3hcl-wupin-interactive'
import { Route as P3hclReadingSyncRouteImport } from './routes/p3hcl-reading-sync'
import { Route as P3hclReading9RouteImport } from './routes/p3hcl-reading-9'
import { Route as P3hclReading12RouteImport } from './routes/p3hcl-reading-12'
import { Route as P3hclReading11RouteImport } from './routes/p3hcl-reading-11'
import { Route as KoushiTrafficSafetyRouteImport } from './routes/koushi-traffic-safety'
import { Route as KoushiNoCivicMindednessRouteImport } from './routes/koushi-no-civic-mindedness'
import { Route as KoushiFamilyCohesionRouteImport } from './routes/koushi-family-cohesion'
import { Route as InstructionsRouteImport } from './routes/instructions'
import { Route as HandwritingRouteImport } from './routes/handwriting'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as Cc1RouteImport } from './routes/cc1'
import { Route as IndexRouteImport } from './routes/index'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuihuWritingRoute = ShuihuWritingRouteImport.update({
  id: '/shuihu-writing',
  path: '/shuihu-writing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolTingxieRoute = SchoolTingxieRouteImport.update({
  id: '/school-tingxie',
  path: '/school-tingxie',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RadicalsRoute = RadicalsRouteImport.update({
  id: '/radicals',
  path: '/radicals',
  getParentRoute: () => rootRouteImport,
} as any)
const PhraseMatchingRoute = PhraseMatchingRouteImport.update({
  id: '/phrase-matching',
  path: '/phrase-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const P3hclWupinInteractiveRoute = P3hclWupinInteractiveRouteImport.update({
  id: '/p3hcl-wupin-interactive',
  path: '/p3hcl-wupin-interactive',
  getParentRoute: () => rootRouteImport,
} as any)
const P3hclReadingSyncRoute = P3hclReadingSyncRouteImport.update({
  id: '/p3hcl-reading-sync',
  path: '/p3hcl-reading-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const P3hclReading9Route = P3hclReading9RouteImport.update({
  id: '/p3hcl-reading-9',
  path: '/p3hcl-reading-9',
  getParentRoute: () => rootRouteImport,
} as any)
const P3hclReading12Route = P3hclReading12RouteImport.update({
  id: '/p3hcl-reading-12',
  path: '/p3hcl-reading-12',
  getParentRoute: () => rootRouteImport,
} as any)
const P3hclReading11Route = P3hclReading11RouteImport.update({
  id: '/p3hcl-reading-11',
  path: '/p3hcl-reading-11',
  getParentRoute: () => rootRouteImport,
} as any)
const KoushiTrafficSafetyRoute = KoushiTrafficSafetyRouteImport.update({
  id: '/koushi-traffic-safety',
  path: '/koushi-traffic-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const KoushiNoCivicMindednessRoute = KoushiNoCivicMindednessRouteImport.update({
  id: '/koushi-no-civic-mindedness',
  path: '/koushi-no-civic-mindedness',
  getParentRoute: () => rootRouteImport,
} as any)
const KoushiFamilyCohesionRoute = KoushiFamilyCohesionRouteImport.update({
  id: '/koushi-family-cohesion',
  path: '/koushi-family-cohesion',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsRoute = InstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const HandwritingRoute = HandwritingRouteImport.update({
  id: '/handwriting',
  path: '/handwriting',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const Cc1Route = Cc1RouteImport.update({
  id: '/cc1',
  path: '/cc1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cc1': typeof Cc1Route
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/family': typeof FamilyRoute
  '/handwriting': typeof HandwritingRoute
  '/instructions': typeof InstructionsRoute
  '/koushi-family-cohesion': typeof KoushiFamilyCohesionRoute
  '/koushi-no-civic-mindedness': typeof KoushiNoCivicMindednessRoute
  '/koushi-traffic-safety': typeof KoushiTrafficSafetyRoute
  '/p3hcl-reading-11': typeof P3hclReading11Route
  '/p3hcl-reading-12': typeof P3hclReading12Route
  '/p3hcl-reading-9': typeof P3hclReading9Route
  '/p3hcl-reading-sync': typeof P3hclReadingSyncRoute
  '/p3hcl-wupin-interactive': typeof P3hclWupinInteractiveRoute
  '/phrase-matching': typeof PhraseMatchingRoute
  '/radicals': typeof RadicalsRoute
  '/review': typeof ReviewRoute
  '/school-tingxie': typeof SchoolTingxieRoute
  '/settings': typeof SettingsRoute
  '/shuihu-writing': typeof ShuihuWritingRoute
  '/vocabulary': typeof VocabularyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cc1': typeof Cc1Route
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/family': typeof FamilyRoute
  '/handwriting': typeof HandwritingRoute
  '/instructions': typeof InstructionsRoute
  '/koushi-family-cohesion': typeof KoushiFamilyCohesionRoute
  '/koushi-no-civic-mindedness': typeof KoushiNoCivicMindednessRoute
  '/koushi-traffic-safety': typeof KoushiTrafficSafetyRoute
  '/p3hcl-reading-11': typeof P3hclReading11Route
  '/p3hcl-reading-12': typeof P3hclReading12Route
  '/p3hcl-reading-9': typeof P3hclReading9Route
  '/p3hcl-reading-sync': typeof P3hclReadingSyncRoute
  '/p3hcl-wupin-interactive': typeof P3hclWupinInteractiveRoute
  '/phrase-matching': typeof PhraseMatchingRoute
  '/radicals': typeof RadicalsRoute
  '/review': typeof ReviewRoute
  '/school-tingxie': typeof SchoolTingxieRoute
  '/settings': typeof SettingsRoute
  '/shuihu-writing': typeof ShuihuWritingRoute
  '/vocabulary': typeof VocabularyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cc1': typeof Cc1Route
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/family': typeof FamilyRoute
  '/handwriting': typeof HandwritingRoute
  '/instructions': typeof InstructionsRoute
  '/koushi-family-cohesion': typeof KoushiFamilyCohesionRoute
  '/koushi-no-civic-mindedness': typeof KoushiNoCivicMindednessRoute
  '/koushi-traffic-safety': typeof KoushiTrafficSafetyRoute
  '/p3hcl-reading-11': typeof P3hclReading11Route
  '/p3hcl-reading-12': typeof P3hclReading12Route
  '/p3hcl-reading-9': typeof P3hclReading9Route
  '/p3hcl-reading-sync': typeof P3hclReadingSyncRoute
  '/p3hcl-wupin-interactive': typeof P3hclWupinInteractiveRoute
  '/phrase-matching': typeof PhraseMatchingRoute
  '/radicals': typeof RadicalsRoute
  '/review': typeof ReviewRoute
  '/school-tingxie': typeof SchoolTingxieRoute
  '/settings': typeof SettingsRoute
  '/shuihu-writing': typeof ShuihuWritingRoute
  '/vocabulary': typeof VocabularyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cc1'
    | '/curriculum'
    | '/dashboard'
    | '/family'
    | '/handwriting'
    | '/instructions'
    | '/koushi-family-cohesion'
    | '/koushi-no-civic-mindedness'
    | '/koushi-traffic-safety'
    | '/p3hcl-reading-11'
    | '/p3hcl-reading-12'
    | '/p3hcl-reading-9'
    | '/p3hcl-reading-sync'
    | '/p3hcl-wupin-interactive'
    | '/phrase-matching'
    | '/radicals'
    | '/review'
    | '/school-tingxie'
    | '/settings'
    | '/shuihu-writing'
    | '/vocabulary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cc1'
    | '/curriculum'
    | '/dashboard'
    | '/family'
    | '/handwriting'
    | '/instructions'
    | '/koushi-family-cohesion'
    | '/koushi-no-civic-mindedness'
    | '/koushi-traffic-safety'
    | '/p3hcl-reading-11'
    | '/p3hcl-reading-12'
    | '/p3hcl-reading-9'
    | '/p3hcl-reading-sync'
    | '/p3hcl-wupin-interactive'
    | '/phrase-matching'
    | '/radicals'
    | '/review'
    | '/school-tingxie'
    | '/settings'
    | '/shuihu-writing'
    | '/vocabulary'
  id:
    | '__root__'
    | '/'
    | '/cc1'
    | '/curriculum'
    | '/dashboard'
    | '/family'
    | '/handwriting'
    | '/instructions'
    | '/koushi-family-cohesion'
    | '/koushi-no-civic-mindedness'
    | '/koushi-traffic-safety'
    | '/p3hcl-reading-11'
    | '/p3hcl-reading-12'
    | '/p3hcl-reading-9'
    | '/p3hcl-reading-sync'
    | '/p3hcl-wupin-interactive'
    | '/phrase-matching'
    | '/radicals'
    | '/review'
    | '/school-tingxie'
    | '/settings'
    | '/shuihu-writing'
    | '/vocabulary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Cc1Route: typeof Cc1Route
  CurriculumRoute: typeof CurriculumRoute
  DashboardRoute: typeof DashboardRoute
  FamilyRoute: typeof FamilyRoute
  HandwritingRoute: typeof HandwritingRoute
  InstructionsRoute: typeof InstructionsRoute
  KoushiFamilyCohesionRoute: typeof KoushiFamilyCohesionRoute
  KoushiNoCivicMindednessRoute: typeof KoushiNoCivicMindednessRoute
  KoushiTrafficSafetyRoute: typeof KoushiTrafficSafetyRoute
  P3hclReading11Route: typeof P3hclReading11Route
  P3hclReading12Route: typeof P3hclReading12Route
  P3hclReading9Route: typeof P3hclReading9Route
  P3hclReadingSyncRoute: typeof P3hclReadingSyncRoute
  P3hclWupinInteractiveRoute: typeof P3hclWupinInteractiveRoute
  PhraseMatchingRoute: typeof PhraseMatchingRoute
  RadicalsRoute: typeof RadicalsRoute
  ReviewRoute: typeof ReviewRoute
  SchoolTingxieRoute: typeof SchoolTingxieRoute
  SettingsRoute: typeof SettingsRoute
  ShuihuWritingRoute: typeof ShuihuWritingRoute
  VocabularyRoute: typeof VocabularyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuihu-writing': {
      id: '/shuihu-writing'
      path: '/shuihu-writing'
      fullPath: '/shuihu-writing'
      preLoaderRoute: typeof ShuihuWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-tingxie': {
      id: '/school-tingxie'
      path: '/school-tingxie'
      fullPath: '/school-tingxie'
      preLoaderRoute: typeof SchoolTingxieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radicals': {
      id: '/radicals'
      path: '/radicals'
      fullPath: '/radicals'
      preLoaderRoute: typeof RadicalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phrase-matching': {
      id: '/phrase-matching'
      path: '/phrase-matching'
      fullPath: '/phrase-matching'
      preLoaderRoute: typeof PhraseMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p3hcl-wupin-interactive': {
      id: '/p3hcl-wupin-interactive'
      path: '/p3hcl-wupin-interactive'
      fullPath: '/p3hcl-wupin-interactive'
      preLoaderRoute: typeof P3hclWupinInteractiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p3hcl-reading-sync': {
      id: '/p3hcl-reading-sync'
      path: '/p3hcl-reading-sync'
      fullPath: '/p3hcl-reading-sync'
      preLoaderRoute: typeof P3hclReadingSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p3hcl-reading-9': {
      id: '/p3hcl-reading-9'
      path: '/p3hcl-reading-9'
      fullPath: '/p3hcl-reading-9'
      preLoaderRoute: typeof P3hclReading9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p3hcl-reading-12': {
      id: '/p3hcl-reading-12'
      path: '/p3hcl-reading-12'
      fullPath: '/p3hcl-reading-12'
      preLoaderRoute: typeof P3hclReading12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p3hcl-reading-11': {
      id: '/p3hcl-reading-11'
      path: '/p3hcl-reading-11'
      fullPath: '/p3hcl-reading-11'
      preLoaderRoute: typeof P3hclReading11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koushi-traffic-safety': {
      id: '/koushi-traffic-safety'
      path: '/koushi-traffic-safety'
      fullPath: '/koushi-traffic-safety'
      preLoaderRoute: typeof KoushiTrafficSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koushi-no-civic-mindedness': {
      id: '/koushi-no-civic-mindedness'
      path: '/koushi-no-civic-mindedness'
      fullPath: '/koushi-no-civic-mindedness'
      preLoaderRoute: typeof KoushiNoCivicMindednessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koushi-family-cohesion': {
      id: '/koushi-family-cohesion'
      path: '/koushi-family-cohesion'
      fullPath: '/koushi-family-cohesion'
      preLoaderRoute: typeof KoushiFamilyCohesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions': {
      id: '/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof InstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwriting': {
      id: '/handwriting'
      path: '/handwriting'
      fullPath: '/handwriting'
      preLoaderRoute: typeof HandwritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cc1': {
      id: '/cc1'
      path: '/cc1'
      fullPath: '/cc1'
      preLoaderRoute: typeof Cc1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Cc1Route: Cc1Route,
  CurriculumRoute: CurriculumRoute,
  DashboardRoute: DashboardRoute,
  FamilyRoute: FamilyRoute,
  HandwritingRoute: HandwritingRoute,
  InstructionsRoute: InstructionsRoute,
  KoushiFamilyCohesionRoute: KoushiFamilyCohesionRoute,
  KoushiNoCivicMindednessRoute: KoushiNoCivicMindednessRoute,
  KoushiTrafficSafetyRoute: KoushiTrafficSafetyRoute,
  P3hclReading11Route: P3hclReading11Route,
  P3hclReading12Route: P3hclReading12Route,
  P3hclReading9Route: P3hclReading9Route,
  P3hclReadingSyncRoute: P3hclReadingSyncRoute,
  P3hclWupinInteractiveRoute: P3hclWupinInteractiveRoute,
  PhraseMatchingRoute: PhraseMatchingRoute,
  RadicalsRoute: RadicalsRoute,
  ReviewRoute: ReviewRoute,
  SchoolTingxieRoute: SchoolTingxieRoute,
  SettingsRoute: SettingsRoute,
  ShuihuWritingRoute: ShuihuWritingRoute,
  VocabularyRoute: VocabularyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
